### ISSUE TITLE
[motherduck-demo] Error when evaluating SSR module ReferenceError: window is not defined

### ISSUE THREAD

**Issue by maxestorr** [dagster-io/devrel-project-demos#19]
# Appearance

"500 | Window is not defined" when starting evidence web server.

## Reproduction Steps

Clone repository, `cd` into motherduck demo, run `make evidence-install` and `make evidence` as described in the Makefile to start the evidence web server in developer mode.

## Logs

```
(venv) maxisq@MS-V-Desktop:~/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute$ make evidence
npm --prefix ./reports run dev -- --port 4000

> my-evidence-project@0.0.1 dev
> evidence dev --open / --port 4000

Starting Evidence development workspace - this can take up to 90 seconds

[!] Unable to load source manifest
        This likely means you have no source data, and need to generate it.
        Running npm run sources will generate the needed data. See npm run sources --help for more usage information
        Documentation: https://docs.evidence.dev/core-concepts/data-sources/
Cleared query cache

Forced re-optimization of dependencies

  VITE v5.1.6  ready in 1050 ms

  ➜  Local:   http://localhost:4000/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
Unable to load manifest, do you need to generate sources?
3:22:06 PM [vite] Error when evaluating SSR module /@fs/home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/@evidence-dev/core-components/dist/unsorted/ui/QueryViewerSupport/QueryDataTable.svelte: failed to import "echarts"
|- ReferenceError: window is not defined
    at detect (/home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/echarts/dist/echarts.js:123:54)
    at /home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/echarts/dist/echarts.js:97:9
    at /home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/echarts/dist/echarts.js:22:68
    at Object.<anonymous> (/home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/echarts/dist/echarts.js:25:2)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at cjsLoader (node:internal/modules/esm/translators:366:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:315:7)

3:22:06 PM [vite] Error when evaluating SSR module /@fs/home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/@evidence-dev/core-components/dist/unsorted/ui/QueryViewer.svelte: failed to import "/@fs/home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/@evidence-dev/core-components/dist/unsorted/ui/QueryViewerSupport/QueryDataTable.svelte"
|- ReferenceError: window is not defined
    at detect (/home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/echarts/dist/echarts.js:123:54)
    at /home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/echarts/dist/echarts.js:97:9
    at /home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/echarts/dist/echarts.js:22:68
    at Object.<anonymous> (/home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/echarts/dist/echarts.js:25:2)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at cjsLoader (node:internal/modules/esm/translators:366:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:315:7)

3:22:06 PM [vite] Error when evaluating SSR module /@fs/home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/@evidence-dev/core-components/dist/unsorted/ui/index.js: failed to import "/@fs/home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/@evidence-dev/core-components/dist/unsorted/ui/QueryViewer.svelte"
|- ReferenceError: window is not defined
    at detect (/home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/echarts/dist/echarts.js:123:54)
    at /home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/echarts/dist/echarts.js:97:9
    at /home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/echarts/dist/echarts.js:22:68
    at Object.<anonymous> (/home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/echarts/dist/echarts.js:25:2)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at cjsLoader (node:internal/modules/esm/translators:366:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:315:7)

3:22:06 PM [vite] Error when evaluating SSR module /@fs/home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/@evidence-dev/core-components/dist/unsorted/index.js: failed to import "/@fs/home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/@evidence-dev/core-components/dist/unsorted/ui/index.js"
|- ReferenceError: window is not defined
    at detect (/home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/echarts/dist/echarts.js:123:54)
    at /home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/echarts/dist/echarts.js:97:9
    at /home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/echarts/dist/echarts.js:22:68
    at Object.<anonymous> (/home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/echarts/dist/echarts.js:25:2)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at cjsLoader (node:internal/modules/esm/translators:366:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:315:7)

3:22:06 PM [vite] Error when evaluating SSR module /@fs/home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/@evidence-dev/core-components/dist/index.js: failed to import "/@fs/home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/@evidence-dev/core-components/dist/unsorted/index.js"
|- ReferenceError: window is not defined
    at detect (/home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/echarts/dist/echarts.js:123:54)
    at /home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/echarts/dist/echarts.js:97:9
    at /home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/echarts/dist/echarts.js:22:68
    at Object.<anonymous> (/home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/echarts/dist/echarts.js:25:2)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at cjsLoader (node:internal/modules/esm/translators:366:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:315:7)

3:22:06 PM [vite] Error when evaluating SSR module /src/pages/+layout.svelte: failed to import "/@fs/home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/@evidence-dev/core-components/dist/index.js"
|- ReferenceError: window is not defined
    at detect (/home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/echarts/dist/echarts.js:123:54)
    at /home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/echarts/dist/echarts.js:97:9
    at /home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/echarts/dist/echarts.js:22:68
    at Object.<anonymous> (/home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/echarts/dist/echarts.js:25:2)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at cjsLoader (node:internal/modules/esm/translators:366:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:315:7)

3:22:06 PM [vite] Error when evaluating SSR module /src/pages/+error.svelte: failed to import "/@fs/home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/@evidence-dev/core-components/dist/index.js"
|- ReferenceError: window is not defined
    at detect (/home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/echarts/dist/echarts.js:123:54)
    at /home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/echarts/dist/echarts.js:97:9
    at /home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/echarts/dist/echarts.js:22:68
    at Object.<anonymous> (/home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/echarts/dist/echarts.js:25:2)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at cjsLoader (node:internal/modules/esm/translators:366:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:315:7)

^Cmake: *** [Makefile:30: evidence] Interrupt
```

**Comment by maxestorr** [comment]
Will submit a PR for a fix soon.

**Comment by cmpadden** [comment]
Resolved in #19 - thanks again.

**Comment by maxestorr** [comment]
Annoyingly as it turns out that fix only allows me to run evidence in dev mode, running `npm run build` still fails as you can see in the snippet below with the same mentioned issue, I'll investigate this:

```shell
(venv) maxisq@MS-V-Desktop:~/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute$ make evidence-build
npm --prefix ./reports run build

> my-evidence-project@0.0.1 build
> evidence build

vite v5.1.6 building SSR bundle for production...

...
skipping irrelevant build logs
...

node:internal/event_target:1096
  process.nextTick(() => { throw err; });
                           ^
ReferenceError [Error]: window is not defined
    at detect (/home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/echarts/dist/echarts.js:123:54)
    at /home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/echarts/dist/echarts.js:97:9
    at /home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/echarts/dist/echarts.js:22:68
    at Object.<anonymous> (/home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/echarts/dist/echarts.js:25:2)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Object..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Function._load (node:internal/modules/cjs/loader:1021:12)
    at cjsLoader (node:internal/modules/esm/translators:366:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:315:7)

Node.js v21.7.1
Build failed

file:///home/maxisq/dev/dagster-devrel-fork/motherduck-dagster-hybrid-compute/reports/node_modules/@evidence-dev/evidence/cli.js:178
                        throw `Build process exited with code ${code}`;
                        ^
Build process exited with code 1
(Use `node --trace-uncaught ...` to show where the exception was thrown)

Node.js v21.7.1
make: *** [Makefile:26: evidence-build] Error 1
```

**Comment by maxestorr** [comment]
This actually happens in a fresh install of evidence, don't know if anyone else wants to try installing via the other options method linked [here](https://docs.evidence.dev/install-evidence/#other-options), then running the following to see if it's just an issue with my system:

`npm install && npm run sources && npm run build`

**Comment by maxestorr** [comment]
Seems like an issue with one of evidence's dependencies since it's occuring even on a fresh install for me, unless I'm somehow grabbing an older version.

In the meantime we can use `make evidence` instead of `make evidence-preview` since it runs just fine in dev mode.

**Comment by cmpadden** [comment]
@maxestorr someone else in their Slack had this issue, and it has to do with using Node v21 instead of Node v20. I was able get this to work by using node version manage ([nvm](https://github.com/nvm-sh/nvm)) to switch to v20, and things seem to be working as expected. I will add a note in the README that this is required.
```
$ nvm use 20
$ npm run build

> my-evidence-project@0.0.1 build
> evidence build

<snip>

✓ built in 30.61s

Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-static
  Wrote site to "build"
  ✔ done
Build complete --> /build
```

**Comment by cmpadden** [comment]
Added a note to use Node v20 here - https://github.com/dagster-io/devrel-project-demos/pull/23/files!
